<?php
return [
    //即时报告
    'requested' => [
        'GET_RESTOCK_INVENTORY_RECOMMENDATIONS_REPORT',
        'GET_AFN_INVENTORY_DATA',
        'GET_FBA_MYI_UNSUPPRESSED_INVENTORY_DATA',
        'GET_FBA_INVENTORY_PLANNING_DATA',
        'GET_FBA_ESTIMATED_FBA_FEES_TXT_DATA',
        'GET_SALES_AND_TRAFFIC_REPORT',
        'GET_SALES_AND_TRAFFIC_REPORT_CUSTOM',
        'GET_FBA_FULFILLMENT_CUSTOMER_RETURNS_DATA',
        'GET_FBA_REIMBURSEMENTS_DATA',
        'GET_FBA_FULFILLMENT_REMOVAL_ORDER_DETAIL_DATA',
        'GET_SELLER_FEEDBACK_DATA',
        'GET_MERCHANT_LISTINGS_ALL_DATA',
        'GET_REFERRAL_FEE_PREVIEW_REPORT',
    ],
    //周期报告
    'schedule' => [
        'GET_V2_SETTLEMENT_REPORT_DATA_FLAT_FILE_V2'
    ]
];